import React, { useState } from 'react';
import { LoaderItem, LoaderConfig } from '../types';
import { X, Check, Copy } from 'lucide-react';

interface CodeModalProps {
  loader: LoaderItem;
  config: LoaderConfig;
  onClose: () => void;
}

const CodeModal: React.FC<CodeModalProps> = ({ loader, config, onClose }) => {
  const [activeTab, setActiveTab] = useState<'html' | 'css'>('html');
  const [copied, setCopied] = useState(false);

  // Generate the CSS with default variable values for better copy-paste experience
  const getProcessedCSS = () => {
    return `/* 
 * ${loader.name}
 * Generated by Loadify
 */
${loader.css}

/* Default Usage Variables */
${loader.html.match(/class="([^"]+)"/)?.[1] ? `.${loader.html.match(/class="([^"]+)"/)?.[1]}` : '.loader'} {
  --loader-color: ${config.color};
  --loader-size: ${config.size}px;
  --loader-speed: ${config.speed}s;
}`;
  };

  const codeToDisplay = activeTab === 'html' ? loader.html : getProcessedCSS();

  const handleCopy = () => {
    navigator.clipboard.writeText(codeToDisplay);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-2xl shadow-2xl animate-fade-in flex flex-col max-h-[90vh]">
        
        <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-900">
          <h2 className="text-lg font-bold text-white px-2">Get Code: <span className="text-blue-400">{loader.name}</span></h2>
          <button onClick={onClose} className="p-2 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex border-b border-slate-800 bg-slate-900/50">
          <button 
            onClick={() => setActiveTab('html')}
            className={`px-6 py-3 text-sm font-medium transition-colors border-b-2 ${activeTab === 'html' ? 'border-blue-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200'}`}
          >
            HTML
          </button>
          <button 
            onClick={() => setActiveTab('css')}
            className={`px-6 py-3 text-sm font-medium transition-colors border-b-2 ${activeTab === 'css' ? 'border-blue-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200'}`}
          >
            CSS
          </button>
        </div>

        <div className="relative flex-1 bg-slate-950 overflow-hidden group">
          <div className="absolute top-4 right-4 z-10">
            <button 
              onClick={handleCopy}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${
                copied 
                  ? 'bg-green-500/10 border-green-500/50 text-green-400' 
                  : 'bg-slate-800 border-slate-700 text-slate-300 hover:border-slate-500 hover:text-white'
              }`}
            >
              {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
              {copied ? 'Copied!' : 'Copy Code'}
            </button>
          </div>
          <pre className="p-6 overflow-auto h-full text-sm font-mono leading-relaxed text-slate-300 selection:bg-blue-500/30">
            <code>{codeToDisplay}</code>
          </pre>
        </div>

        <div className="p-4 bg-slate-900 border-t border-slate-800 text-xs text-slate-500">
          Tip: Paste the CSS into your stylesheet and the HTML into your component.
        </div>
      </div>
    </div>
  );
};

export default CodeModal;
